//
//  File.swift
//
//
//  Created by Junior Quevedo Gutiérrez  on 1/04/24.
//

import Foundation
import SwiftUI

public extension DDDIcon {
    enum Images: CaseIterable, Identifiable {
        public var id: String { return self.hashValue.description }

        case arrowDown
        case arrowLeft
        case arrowRight
        case arrowUpRight
        case arrowUp
        case chevronDown
        case chevronLeft
        case chevronRight
        case chevronUp
        case grid
        case maximize2
        case minimize2
        case add
        case alertCircle
        case alertTriangle
        case chevronDownFill
        case chevronUpFill
        case circle
        case clock
        case collections
        case delete
        case download
        case externalLink
        case filter
        case gift
        case globe
        case heart
        case helpCircle
        case home
        case info
        case lifeBuoy
        case mail
        case mapPin
        case map
        case restaurant
        case share2
        case slash
        case trendingTopic
        case trendingDown
        case trendingUp
        case zap
        case award2
        case award
        case calendar
        case check
        case dollarSign
        case edit2
        case eyeOff
        case eye
        case image
        case like
        case list
        case loader
        case lock
        case menuFood
        case minus
        case moreHorizontal
        case moreVertical
        case navigation
        case phone
        case plus
        case premium
        case promo
        case refreshCcw
        case search
        case send
        case settings
        case share
        case smile
        case star
        case trash2
        case unlock
        case upload
        case wifi
        case x
        case anticuchos
        case chicken
        case delivery
        case privacy
        case bell
        case booking
        case cafe
        case creditCard
        case eatInRestaurant
        case estacionamiento
        case food
        case glow
        case happyHour
        case kidsPlay
        case music
        case payment
        case terms
        case terrace
        case apple
        case facebook
        case google
        case instagram
        case twitter
        case agend
        case aquisito
        case fotocheck
        case user
        
        public var image: ImageAsset {
            switch self {
                
            case .arrowDown:
                ImageAsset(name: "arrow-down")
            case .arrowLeft:
                ImageAsset(name: "arrow-left")
            case .arrowRight:
                ImageAsset(name: "arrow-right")
            case .arrowUpRight:
                ImageAsset(name: "arrow-up-right")
            case .arrowUp:
                ImageAsset(name: "arrow-up")
            case .chevronDown:
                ImageAsset(name: "chevron-down")
            case .chevronLeft:
                ImageAsset(name: "chevron-left")
            case .chevronRight:
                ImageAsset(name: "chevron-right")
            case .chevronUp:
                ImageAsset(name: "chevron-up")
            case .grid:
                ImageAsset(name: "grid")
            case .maximize2:
                ImageAsset(name: "maximize-2")
            case .minimize2:
                ImageAsset(name: "minimize-2")
            case .add:
                ImageAsset(name: "add")
            case .alertCircle:
                ImageAsset(name: "alert-circle")
            case .alertTriangle:
                ImageAsset(name: "alert-triangle")
            case .chevronDownFill:
                ImageAsset(name: "chevron-down-fill")
            case .chevronUpFill:
                ImageAsset(name: "chevron-up-fill")
            case .circle:
                ImageAsset(name: "circle")
            case .clock:
                ImageAsset(name: "clock")
            case .collections:
                ImageAsset(name: "collections")
            case .delete:
                ImageAsset(name: "delete")
            case .download:
                ImageAsset(name: "download")
            case .externalLink:
                ImageAsset(name: "external-link")
            case .filter:
                ImageAsset(name: "filter")
            case .gift:
                ImageAsset(name: "gift")
            case .globe:
                ImageAsset(name: "globe")
            case .heart:
                ImageAsset(name: "heart")
            case .helpCircle:
                ImageAsset(name: "help-circle")
            case .home:
                ImageAsset(name: "home")
            case .info:
                ImageAsset(name: "info")
            case .lifeBuoy:
                ImageAsset(name: "life-buoy")
            case .mail:
                ImageAsset(name: "mail")
            case .mapPin:
                ImageAsset(name: "map-pin")
            case .map:
                ImageAsset(name: "map")
            case .restaurant:
                ImageAsset(name: "restaurant")
            case .share2:
                ImageAsset(name: "share-2")
            case .slash:
                ImageAsset(name: "slash")
            case .trendingTopic:
                ImageAsset(name: "trending topic")
            case .trendingDown:
                ImageAsset(name: "trending-down")
            case .trendingUp:
                ImageAsset(name: "trending-up")
            case .zap:
                ImageAsset(name: "zap")
            case .award2:
                ImageAsset(name: "award 2")
            case .award:
                ImageAsset(name: "award")
            case .calendar:
                ImageAsset(name: "calendar")
            case .check:
                ImageAsset(name: "check")
            case .dollarSign:
                ImageAsset(name: "dollar-sign")
            case .edit2:
                ImageAsset(name: "edit-2")
            case .eyeOff:
                ImageAsset(name: "eye-off")
            case .eye:
                ImageAsset(name: "eye")
            case .image:
                ImageAsset(name: "image")
            case .like:
                ImageAsset(name: "like")
            case .list:
                ImageAsset(name: "list")
            case .loader:
                ImageAsset(name: "loader")
            case .lock:
                ImageAsset(name: "lock")
            case .menuFood:
                ImageAsset(name: "menu food")
            case .minus:
                ImageAsset(name: "minus")
            case .moreHorizontal:
                ImageAsset(name: "more-horizontal")
            case .moreVertical:
                ImageAsset(name: "more-vertical")
            case .navigation:
                ImageAsset(name: "navigation")
            case .phone:
                ImageAsset(name: "phone")
            case .plus:
                ImageAsset(name: "plus")
            case .premium:
                ImageAsset(name: "premium")
            case .promo:
                ImageAsset(name: "promo")
            case .refreshCcw:
                ImageAsset(name: "refresh-ccw")
            case .search:
                ImageAsset(name: "search")
            case .send:
                ImageAsset(name: "send")
            case .settings:
                ImageAsset(name: "settings")
            case .share:
                ImageAsset(name: "share")
            case .smile:
                ImageAsset(name: "smile")
            case .star:
                ImageAsset(name: "star")
            case .trash2:
                ImageAsset(name: "trash-2")
            case .unlock:
                ImageAsset(name: "unlock")
            case .upload:
                ImageAsset(name: "upload")
            case .wifi:
                ImageAsset(name: "wifi")
            case .x:
                ImageAsset(name: "x")
            case .anticuchos:
                ImageAsset(name: "Anticuchos")
            case .chicken:
                ImageAsset(name: "Chicken")
            case .delivery:
                ImageAsset(name: "Delivery")
            case .privacy:
                ImageAsset(name: "Privacy")
            case .bell:
                ImageAsset(name: "bell")
            case .booking:
                ImageAsset(name: "booking")
            case .cafe:
                ImageAsset(name: "cafe")
            case .creditCard:
                ImageAsset(name: "credit card")
            case .eatInRestaurant:
                ImageAsset(name: "eat in restaurant")
            case .estacionamiento:
                ImageAsset(name: "estacionamiento")
            case .food:
                ImageAsset(name: "food")
            case .glow:
                ImageAsset(name: "glow")
            case .happyHour:
                ImageAsset(name: "happy hour")
            case .kidsPlay:
                ImageAsset(name: "kids play")
            case .music:
                ImageAsset(name: "music")
            case .payment:
                ImageAsset(name: "payment")
            case .terms:
                ImageAsset(name: "terms")
            case .terrace:
                ImageAsset(name: "terrace")
            case .apple:
                ImageAsset(name: "Apple")
            case .facebook:
                ImageAsset(name: "Facebook")
            case .google:
                ImageAsset(name: "Google")
            case .instagram:
                ImageAsset(name: "Instagram")
            case .twitter:
                ImageAsset(name: "Twitter")
            case .agend:
                ImageAsset(name: "agend")
            case .aquisito:
                ImageAsset(name: "aquisito")
            case .fotocheck:
                ImageAsset(name: "fotocheck")
            case .user:
                ImageAsset(name: "user")
            }
        }

    }
    
}
